"use client"

import { Providers } from "@/components/providers/Provodirs"
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import {Sidebar, SidebarItem} from "@/components/Sidebar";
import { CircleCheckBig, CopyPlus, HelpCircle, Home, LifeBuoy, ListChecks, Settings } from "lucide-react";
import ExpandIcon from "@/components/ExpandIcon";
import { SidebarProvider } from "@/components/providers/SidebarProvider";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import DashboardShell from "@/components/DashShell";

const queryClient = new QueryClient()

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export default function DashboardLayout({children}: {
    children: React.ReactNode
}) {
    return(
    <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
            
            <Providers>
              <SidebarProvider>
              <QueryClientProvider client={queryClient}>
                <DashboardShell>
                  {children}
                </DashboardShell>
              </QueryClientProvider>
            </SidebarProvider>
            </Providers>
            
        </body>
    </html>
    );
}