import { Providers } from "@/components/Provodirs"
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import {Sidebar, SidebarItem} from "@/components/Sidebar";
import { CircleCheckBig, CopyPlus, HelpCircle, Home, LifeBuoy, ListChecks, Settings } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function DashboardLayout({children}: {
    children: React.ReactNode
}) {
    return(
    <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
            <Providers>
              <div className="flex">
                <Sidebar>
                  <SidebarItem icon={<Home size={20} />} text="Dashboard" href="/dashboard"/>
                  <SidebarItem icon={<CopyPlus size={20} />} text="Add Task" href="/dashboard/add-tasks" />
                  <SidebarItem icon={<ListChecks size={20} />} text="My Tasks" href="/dashboard/tasks" />
                  <SidebarItem icon={<CircleCheckBig size={20} />} text="Completed Tasks" href="/dashboard/completed-tasks" />
                  <hr className="my-3" />
                  <SidebarItem icon={<Settings size={20} />} text="Settings" href="/dashboard/settings" />
                  <SidebarItem icon={<HelpCircle size={20} />} text="Help" href="/dashboard/help" />
                </Sidebar>
                {children}
              </div>
            
            </Providers>
        </body>
    </html>
    );
}